apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-function-rhos
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-function-rhos
  namespace: backend
spec:
  source:
    git:
      url: https://github.com/fabianbrash/node-function-rhos.git
      ref:
        branch: main
