apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-function-rhos
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-function-rhos
spec:
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
